
export const ingredients = [
    '1/2 cup fresh basil leaves',
    '1/2 cup fresh mint leaves',
    '1/2 cup fresh cilantro leaves',
    '1/2 cup fresh parsley leaves',
    '1/4 cup fresh oregano leaves',
    '1/4 cup fresh rosemary leaves',
    '1/4 cup fresh thyme leaves',
    '1/4 cup fresh tarragon leaves',
    '1/4 cup fresh dill leaves',
    '1/4 cup fresh sage leaves',
    '1/4 cup fresh marjoram leaves',
    '1/4 cup fresh chives',
    '1/4 cup fresh lemon balm leaves',
    '1/4 cup fresh lemon verbena leaves',
    '1/4 cup fresh lemon thyme leaves',
    '1/4 cup fresh lemon basil leaves',
    '1/4 cup fresh lemongrass leaves',
    '1/4 cup fresh lemon mint leaves',
    '1/4 cup fresh lemon balm leaves',
    '1/4 cup fresh lemon verbena leaves',
    '1/4 cup fresh lemon thyme leaves',
    '1/4 cup fresh lemon basil leaves',
    '1/4 cup fresh lemongrass leaves',
    '1/4 cup fresh lemon mint leaves',
    '1/4 cup fresh lemon balm leaves',
    '1/4 cup fresh lemon verbena leaves',
    '1/4 cup fresh lemon thyme leaves',
    '1/4 cup fresh lemon basil leaves',
    '1/4 cup fresh lemongrass leaves',
    '1/4 cup fresh lemon mint leaves',
];

export const steps = [
    'Wash the herbs and pat dry.',
    'Remove the leaves from the stems.',
    'Place the leaves in a single layer on a baking sheet.',
    'Freeze for 2 hours.',
    'Transfer the frozen leaves to a freezer bag or container.',
    'Label the bag or container with the name of the herb and the date.',
    'Store in the freezer for up to 6 months.',
    'Use the frozen herbs in soups, stews, and sauces.',
    'You can also use them to make herb butter or herb-infused oil.',
    'To make herb butter, mix 1/2 cup of softened butter with 1 tablespoon of chopped herbs.',
    'To make herb-infused oil, mix 1/2 cup of olive oil with 1 tablespoon of chopped herbs.',
    'Store the herb butter or oil in the refrigerator for up to 1 week.',
    'You can also freeze the herb butter or oil in ice cube trays for up to 3 months.',
    'To use the frozen herb butter or oil, simply thaw it in the refrigerator overnight.',
    'You can also use the frozen herb butter or oil in place of regular butter or oil in your favorite recipes.',
    'You can also use the frozen herb butter or oil in place of regular butter or oil in your favorite recipes.',
];